# Generated by Django 4.0.2 on 2022-07-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_dish_isglutenfree_alter_dish_isvegeterian'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='remove',
            field=models.BooleanField(default=False),
        ),
    ]
