# Generated by Django 4.0.2 on 2022-07-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dish_remove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='remove',
        ),
    ]
