# Generated by Django 4.0.2 on 2022-07-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
